
<style>
.wizit-popup-body-content iframe{
    width: 100%;
    min-height: 920px;
}

</style>



<div id="wizit-modal-content">
    <div class="modal-body-content wizit-popup-body-content">
        <iframe id="wizit-popup-iframe" title="Terms and Conditions">
        </iframe>
    </div>    
</div>



<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            title: 'Terms and Conditions',
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    // unload iframe
                    document.getElementById('wizit-popup-iframe').setAttribute("src","");
                    // close modal
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#wizit-modal-content'));
        $(".wizit-learn-more-popup-link").click(function() {
            // set iframe url
            document.getElementById('wizit-popup-iframe').setAttribute("src","https://info.wizit.com.au/HowItWorks/HowItWorks.html");
            // load modal
            $('#wizit-modal-content').modal('openModal');
        });
    });
</script>